### ISSUE TITLE
What happened to the extension?

### ISSUE THREAD

**Issue by Long-Horse** [madhur/dashclock-feedly-extension#5]
I don't see it on the Play Store. Was it removed?

**Comment by madhur** [comment]
Its named Feed Notifier
https://play.google.com/store/apps/details?id=in.co.madhur.dashclockfeedlyextension&hl=en

**Comment by Long-Horse** [comment]
I never knew about that but I had this extension for a while:

http://imgur.com/xaE2vHe

http://imgur.com/khGqfdZ

And I can't get your app to show in Dashclock

**Comment by madhur** [comment]
The app in your screenshot seems to be official feedly app
https://play.google.com/store/apps/details?id=com.devhd.feedly&hl=en

**Comment by Long-Horse** [comment]
Oh I didn;t realize that was the official app. I guess it's been a while since I set up dashclock. But then what's the point of yours if the official one exists? Also I tried yours but it was reporting inaccurately.

**Comment by madhur** [comment]
Mine is a notifier. Official app does not support notifications.
